### ISSUE TITLE
BUG: printing the results of rowWelchTests

### ISSUE THREAD

**Issue by pneuvial** [pneuvial/sanssouci#11]
The output of `rowWelchTests` should not be of class `htest`: currently `stats:::print.htest` returns unexpected results and fails for larger number of tests.

Example:

```
n <- 38
mat <- matrix(rnorm(10*n), ncol=n)
cls <- rep(c(0, 1), times=c(27, n-27))
fwt <- rowWelchTests(mat, categ=cls)
fwt
```
yields

    data:
    = 0.023468, = 1.906200, = -1.624400, = 1.700900, = -0.010300, =
    -0.059971, = -1.035200, = 1.369600, = -0.709590, = 0.865390, = 26.498,
    = 17.024, = 24.786, = 23.283, = 18.480, = 16.642, = 16.898, = 19.323, =
    19.993, = 16.878, p-value = 0.98145, p-value = 0.07365, p-value =
    0.11695, p-value = 0.10228, p-value = 0.99189, p-value = 0.95289,
    p-value = 0.31515, p-value = 0.18653, p-value = 0.48615, p-value =
    0.39896
    
    Warning message:
    In if (substr(fp, 1L, 1L) == "<") fp else paste("=", fp) :
      the condition has length > 1 and only the first element will be used

**Comment by KKPMW** [comment]
Hello,

Just wanted to leave a short comment for information: a while ago we briefly talked about rowWilcoxon tests in `matrixStats` discussion and I mentioned that I was working on them for my `matrixTests` package.

A couple of months ago `row_wilcoxon_*` tests were implemented in `matrixTests`. Feel free to use it if applicable, or look at the source code for ideas about how to vectorise exact version of this test.
