### ISSUE TITLE
Add pvalue axis and calibration threshold axis

### ISSUE THREAD

**Issue by nicolas-enjalbert** [pneuvial/sanssouci#30]

**Comment by nicolas-enjalbert** [comment]
Add a radio button to chose y axis between : 
 - pvalue : classical volcano plot
 - adjusted p values : print some classical adj. pvalues (0.1, 0.05, 0.001)
 - 10 first threshold from calibration

**Comment by pneuvial** [comment]
When I choose "adjusted p-values" or "calibration threshold" I get an error: "object 'adjp' not found". 
Probably 'adjp' is in your global environment and not in mine!
