### ISSUE TITLE
Accelerate y-axis reactions

### ISSUE THREAD

**Issue by nicolas-enjalbert** [pneuvial/sanssouci#34]
Reactive only the corresponding plotly level for this change

**Comment by nicolas-enjalbert** [comment]
According to https://plotly-r.com/linking-views-with-shiny.html and the example at `plotly_example("shiny", "proxy_relayout")` in R, 
to improve reactivity for the y-axis change, the following code is used:
`plotlyProxy("volcanoplot", session) %>%
      plotlyProxyInvoke("relayout", list(yaxis = yaxis))`

'relayout' let point the change in the 'layout' of the plotly object named "volcanoplot".

**Comment by pneuvial** [comment]
Very nice! :+1:
